name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix: #, macos-latest, windows-latest
        os: [ubuntu-latest]
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.15.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: 'admin/pnpm-lock.yaml'

      - name: Setup frontend
        working-directory: admin
        run: |
          pnpm install
          pnpm build

      - name: Prepare deployment files
        run: |
          mkdir -p deploy
          cp -r docker deploy/
          cp -r sql deploy/
          mkdir -p deploy/admin
          cp -r admin/dist deploy/admin/
          mkdir -p deploy/server
          cp -r server/Dockerfile deploy/server/

      - name: Debug Variables
        run: |
          echo "Checking Repository Variables:"
          echo "777777777 vars: ${{ vars }}"
          echo "REMOTE_HOST: ${{ vars.REMOTE_HOST }}"
          echo "REMOTE_USER: ${{ vars.REMOTE_USER }}"
          echo "TARGET: ${{ vars.TARGET }}"
          echo "SSH_PRIVATE_KEY: ${{ vars.SSH_PRIVATE_KEY }}"
          echo "777777777 secrets: ${{ secrets }}"
          echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ vars.REMOTE_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ vars.SSH_PRIVATE_KEY }}

      - name: SSH Deploy
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ vars.SSH_PRIVATE_KEY }}
          ARGS: '-avzr --delete'
          SOURCE: 'deploy/'
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          TARGET: ${{ vars.TARGET }}

      - name: Execute Docker container
        run: |
          ssh ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }} "cd ${{ vars.TARGET }}/docker && docker-compose up -d"
